//3rd graph - owner
import { useEffect } from 'react'

export default function Owner() {
  useEffect(() => {
    window.PLOTLYENV = window.PLOTLYENV || {}
    if (document.getElementById('bbc70df4-65c8-4f19-a70c-0485833025e3')) {
      window.Plotly.newPlot(
        'bbc70df4-65c8-4f19-a70c-0485833025e3',
        [
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'NextEra Energy',
            marker: { color: 'rgb(224, 253, 74)', pattern: { shape: '' } },
            name: 'NextEra Energy',
            offsetgroup: 'NextEra Energy',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['NextEra Energy'],
            xaxis: 'x',
            y: [140],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'CECEP Solar Energy Technology Co., Ltd.',
            marker: { color: 'rgb(222, 222, 59)', pattern: { shape: '' } },
            name: 'CECEP Solar Energy Technology Co., Ltd.',
            offsetgroup: 'CECEP Solar Energy Technology Co., Ltd.',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['CECEP Solar Energy Technology Co., Ltd.'],
            xaxis: 'x',
            y: [82],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'CGN Solar Energy Development Co., Ltd.',
            marker: { color: 'rgb(217, 192, 44)', pattern: { shape: '' } },
            name: 'CGN Solar Energy Development Co., Ltd.',
            offsetgroup: 'CGN Solar Energy Development Co., Ltd.',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['CGN Solar Energy Development Co., Ltd.'],
            xaxis: 'x',
            y: [70],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'Solatio Energia',
            marker: { color: 'rgb(209, 164, 32)', pattern: { shape: '' } },
            name: 'Solatio Energia',
            offsetgroup: 'Solatio Energia',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['Solatio Energia'],
            xaxis: 'x',
            y: [62],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'Adani Green Energy',
            marker: { color: 'rgb(199, 137, 22)', pattern: { shape: '' } },
            name: 'Adani Green Energy',
            offsetgroup: 'Adani Green Energy',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['Adani Green Energy'],
            xaxis: 'x',
            y: [56],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'China Nuclear Exchange Energy Co., Ltd.',
            marker: { color: 'rgb(188, 111, 19)', pattern: { shape: '' } },
            name: 'China Nuclear Exchange Energy Co., Ltd.',
            offsetgroup: 'China Nuclear Exchange Energy Co., Ltd.',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['China Nuclear Exchange Energy Co., Ltd.'],
            xaxis: 'x',
            y: [55],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'EDF Renewables',
            marker: { color: 'rgb(174, 88, 20)', pattern: { shape: '' } },
            name: 'EDF Renewables',
            offsetgroup: 'EDF Renewables',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['EDF Renewables'],
            xaxis: 'x',
            y: [53],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'China Three Gorges New Energy (Group) Co., Ltd.',
            marker: { color: 'rgb(157, 66, 25)', pattern: { shape: '' } },
            name: 'China Three Gorges New Energy (Group) Co., Ltd.',
            offsetgroup: 'China Three Gorges New Energy (Group) Co., Ltd.',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['China Three Gorges New Energy (Group) Co., Ltd.'],
            xaxis: 'x',
            y: [52],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'Dominion Energy',
            marker: { color: 'rgb(135, 47, 32)', pattern: { shape: '' } },
            name: 'Dominion Energy',
            offsetgroup: 'Dominion Energy',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['Dominion Energy'],
            xaxis: 'x',
            y: [50],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
          {
            alignmentgroup: 'True',
            hovertemplate:
              '<b>Owner:</b> %{x}<br><b>Owned solar farms:</b> %{y}',
            legendgroup: 'Duke Energy',
            marker: { color: 'rgb(108, 36, 36)', pattern: { shape: '' } },
            name: 'Duke Energy',
            offsetgroup: 'Duke Energy',
            orientation: 'v',
            showlegend: true,
            textposition: 'auto',
            x: ['Duke Energy'],
            xaxis: 'x',
            y: [48],
            yaxis: 'y',
            type: 'bar',
            hoverlabel: { bgcolor: 'gold', bordercolor: 'rebeccapurple' },
          },
        ],
        {
          template: {
            data: {
              histogram2dcontour: [
                {
                  type: 'histogram2dcontour',
                  colorbar: { outlinewidth: 0, ticks: '' },
                  colorscale: [
                    [0.0, '#0d0887'],
                    [0.1111111111111111, '#46039f'],
                    [0.2222222222222222, '#7201a8'],
                    [0.3333333333333333, '#9c179e'],
                    [0.4444444444444444, '#bd3786'],
                    [0.5555555555555556, '#d8576b'],
                    [0.6666666666666666, '#ed7953'],
                    [0.7777777777777778, '#fb9f3a'],
                    [0.8888888888888888, '#fdca26'],
                    [1.0, '#f0f921'],
                  ],
                },
              ],
              choropleth: [
                {
                  type: 'choropleth',
                  colorbar: { outlinewidth: 0, ticks: '' },
                },
              ],
              histogram2d: [
                {
                  type: 'histogram2d',
                  colorbar: { outlinewidth: 0, ticks: '' },
                  colorscale: [
                    [0.0, '#0d0887'],
                    [0.1111111111111111, '#46039f'],
                    [0.2222222222222222, '#7201a8'],
                    [0.3333333333333333, '#9c179e'],
                    [0.4444444444444444, '#bd3786'],
                    [0.5555555555555556, '#d8576b'],
                    [0.6666666666666666, '#ed7953'],
                    [0.7777777777777778, '#fb9f3a'],
                    [0.8888888888888888, '#fdca26'],
                    [1.0, '#f0f921'],
                  ],
                },
              ],
              heatmap: [
                {
                  type: 'heatmap',
                  colorbar: { outlinewidth: 0, ticks: '' },
                  colorscale: [
                    [0.0, '#0d0887'],
                    [0.1111111111111111, '#46039f'],
                    [0.2222222222222222, '#7201a8'],
                    [0.3333333333333333, '#9c179e'],
                    [0.4444444444444444, '#bd3786'],
                    [0.5555555555555556, '#d8576b'],
                    [0.6666666666666666, '#ed7953'],
                    [0.7777777777777778, '#fb9f3a'],
                    [0.8888888888888888, '#fdca26'],
                    [1.0, '#f0f921'],
                  ],
                },
              ],
              heatmapgl: [
                {
                  type: 'heatmapgl',
                  colorbar: { outlinewidth: 0, ticks: '' },
                  colorscale: [
                    [0.0, '#0d0887'],
                    [0.1111111111111111, '#46039f'],
                    [0.2222222222222222, '#7201a8'],
                    [0.3333333333333333, '#9c179e'],
                    [0.4444444444444444, '#bd3786'],
                    [0.5555555555555556, '#d8576b'],
                    [0.6666666666666666, '#ed7953'],
                    [0.7777777777777778, '#fb9f3a'],
                    [0.8888888888888888, '#fdca26'],
                    [1.0, '#f0f921'],
                  ],
                },
              ],
              contourcarpet: [
                {
                  type: 'contourcarpet',
                  colorbar: { outlinewidth: 0, ticks: '' },
                },
              ],
              contour: [
                {
                  type: 'contour',
                  colorbar: { outlinewidth: 0, ticks: '' },
                  colorscale: [
                    [0.0, '#0d0887'],
                    [0.1111111111111111, '#46039f'],
                    [0.2222222222222222, '#7201a8'],
                    [0.3333333333333333, '#9c179e'],
                    [0.4444444444444444, '#bd3786'],
                    [0.5555555555555556, '#d8576b'],
                    [0.6666666666666666, '#ed7953'],
                    [0.7777777777777778, '#fb9f3a'],
                    [0.8888888888888888, '#fdca26'],
                    [1.0, '#f0f921'],
                  ],
                },
              ],
              surface: [
                {
                  type: 'surface',
                  colorbar: { outlinewidth: 0, ticks: '' },
                  colorscale: [
                    [0.0, '#0d0887'],
                    [0.1111111111111111, '#46039f'],
                    [0.2222222222222222, '#7201a8'],
                    [0.3333333333333333, '#9c179e'],
                    [0.4444444444444444, '#bd3786'],
                    [0.5555555555555556, '#d8576b'],
                    [0.6666666666666666, '#ed7953'],
                    [0.7777777777777778, '#fb9f3a'],
                    [0.8888888888888888, '#fdca26'],
                    [1.0, '#f0f921'],
                  ],
                },
              ],
              mesh3d: [
                { type: 'mesh3d', colorbar: { outlinewidth: 0, ticks: '' } },
              ],
              scatter: [
                {
                  fillpattern: { fillmode: 'overlay', size: 10, solidity: 0.2 },
                  type: 'scatter',
                },
              ],
              parcoords: [
                {
                  type: 'parcoords',
                  line: { colorbar: { outlinewidth: 0, ticks: '' } },
                },
              ],
              scatterpolargl: [
                {
                  type: 'scatterpolargl',
                  marker: { colorbar: { outlinewidth: 0, ticks: '' } },
                },
              ],
              bar: [
                {
                  error_x: { color: '#2a3f5f' },
                  error_y: { color: '#2a3f5f' },
                  marker: {
                    line: { color: '#E5ECF6', width: 0.5 },
                    pattern: { fillmode: 'overlay', size: 10, solidity: 0.2 },
                  },
                  type: 'bar',
                },
              ],
              scattergeo: [
                {
                  type: 'scattergeo',
                  marker: { colorbar: { outlinewidth: 0, ticks: '' } },
                },
              ],
              scatterpolar: [
                {
                  type: 'scatterpolar',
                  marker: { colorbar: { outlinewidth: 0, ticks: '' } },
                },
              ],
              histogram: [
                {
                  marker: {
                    pattern: { fillmode: 'overlay', size: 10, solidity: 0.2 },
                  },
                  type: 'histogram',
                },
              ],
              scattergl: [
                {
                  type: 'scattergl',
                  marker: { colorbar: { outlinewidth: 0, ticks: '' } },
                },
              ],
              scatter3d: [
                {
                  type: 'scatter3d',
                  line: { colorbar: { outlinewidth: 0, ticks: '' } },
                  marker: { colorbar: { outlinewidth: 0, ticks: '' } },
                },
              ],
              scattermapbox: [
                {
                  type: 'scattermapbox',
                  marker: { colorbar: { outlinewidth: 0, ticks: '' } },
                },
              ],
              scatterternary: [
                {
                  type: 'scatterternary',
                  marker: { colorbar: { outlinewidth: 0, ticks: '' } },
                },
              ],
              scattercarpet: [
                {
                  type: 'scattercarpet',
                  marker: { colorbar: { outlinewidth: 0, ticks: '' } },
                },
              ],
              carpet: [
                {
                  aaxis: {
                    endlinecolor: '#2a3f5f',
                    gridcolor: 'white',
                    linecolor: 'white',
                    minorgridcolor: 'white',
                    startlinecolor: '#2a3f5f',
                  },
                  baxis: {
                    endlinecolor: '#2a3f5f',
                    gridcolor: 'white',
                    linecolor: 'white',
                    minorgridcolor: 'white',
                    startlinecolor: '#2a3f5f',
                  },
                  type: 'carpet',
                },
              ],
              table: [
                {
                  cells: {
                    fill: { color: '#EBF0F8' },
                    line: { color: 'white' },
                  },
                  header: {
                    fill: { color: '#C8D4E3' },
                    line: { color: 'white' },
                  },
                  type: 'table',
                },
              ],
              barpolar: [
                {
                  marker: {
                    line: { color: '#E5ECF6', width: 0.5 },
                    pattern: { fillmode: 'overlay', size: 10, solidity: 0.2 },
                  },
                  type: 'barpolar',
                },
              ],
              pie: [{ automargin: true, type: 'pie' }],
            },
            layout: {
              autotypenumbers: 'strict',
              colorway: [
                '#636efa',
                '#EF553B',
                '#00cc96',
                '#ab63fa',
                '#FFA15A',
                '#19d3f3',
                '#FF6692',
                '#B6E880',
                '#FF97FF',
                '#FECB52',
              ],
              font: { color: '#2a3f5f' },
              hovermode: 'closest',
              hoverlabel: { align: 'left' },
              paper_bgcolor: 'white',
              plot_bgcolor: '#E5ECF6',
              polar: {
                bgcolor: '#E5ECF6',
                angularaxis: {
                  gridcolor: 'white',
                  linecolor: 'white',
                  ticks: '',
                },
                radialaxis: {
                  gridcolor: 'white',
                  linecolor: 'white',
                  ticks: '',
                },
              },
              ternary: {
                bgcolor: '#E5ECF6',
                aaxis: { gridcolor: 'white', linecolor: 'white', ticks: '' },
                baxis: { gridcolor: 'white', linecolor: 'white', ticks: '' },
                caxis: { gridcolor: 'white', linecolor: 'white', ticks: '' },
              },
              coloraxis: { colorbar: { outlinewidth: 0, ticks: '' } },
              colorscale: {
                sequential: [
                  [0.0, '#0d0887'],
                  [0.1111111111111111, '#46039f'],
                  [0.2222222222222222, '#7201a8'],
                  [0.3333333333333333, '#9c179e'],
                  [0.4444444444444444, '#bd3786'],
                  [0.5555555555555556, '#d8576b'],
                  [0.6666666666666666, '#ed7953'],
                  [0.7777777777777778, '#fb9f3a'],
                  [0.8888888888888888, '#fdca26'],
                  [1.0, '#f0f921'],
                ],
                sequentialminus: [
                  [0.0, '#0d0887'],
                  [0.1111111111111111, '#46039f'],
                  [0.2222222222222222, '#7201a8'],
                  [0.3333333333333333, '#9c179e'],
                  [0.4444444444444444, '#bd3786'],
                  [0.5555555555555556, '#d8576b'],
                  [0.6666666666666666, '#ed7953'],
                  [0.7777777777777778, '#fb9f3a'],
                  [0.8888888888888888, '#fdca26'],
                  [1.0, '#f0f921'],
                ],
                diverging: [
                  [0, '#8e0152'],
                  [0.1, '#c51b7d'],
                  [0.2, '#de77ae'],
                  [0.3, '#f1b6da'],
                  [0.4, '#fde0ef'],
                  [0.5, '#f7f7f7'],
                  [0.6, '#e6f5d0'],
                  [0.7, '#b8e186'],
                  [0.8, '#7fbc41'],
                  [0.9, '#4d9221'],
                  [1, '#276419'],
                ],
              },
              xaxis: {
                gridcolor: 'white',
                linecolor: 'white',
                ticks: '',
                title: { standoff: 15 },
                zerolinecolor: 'white',
                automargin: true,
                zerolinewidth: 2,
              },
              yaxis: {
                gridcolor: 'white',
                linecolor: 'white',
                ticks: '',
                title: { standoff: 15 },
                zerolinecolor: 'white',
                automargin: true,
                zerolinewidth: 2,
              },
              scene: {
                xaxis: {
                  backgroundcolor: '#E5ECF6',
                  gridcolor: 'white',
                  linecolor: 'white',
                  showbackground: true,
                  ticks: '',
                  zerolinecolor: 'white',
                  gridwidth: 2,
                },
                yaxis: {
                  backgroundcolor: '#E5ECF6',
                  gridcolor: 'white',
                  linecolor: 'white',
                  showbackground: true,
                  ticks: '',
                  zerolinecolor: 'white',
                  gridwidth: 2,
                },
                zaxis: {
                  backgroundcolor: '#E5ECF6',
                  gridcolor: 'white',
                  linecolor: 'white',
                  showbackground: true,
                  ticks: '',
                  zerolinecolor: 'white',
                  gridwidth: 2,
                },
              },
              shapedefaults: { line: { color: '#2a3f5f' } },
              annotationdefaults: {
                arrowcolor: '#2a3f5f',
                arrowhead: 0,
                arrowwidth: 1,
              },
              geo: {
                bgcolor: 'white',
                landcolor: '#E5ECF6',
                subunitcolor: 'white',
                showland: true,
                showlakes: true,
                lakecolor: 'white',
              },
              title: { x: 0.05 },
              mapbox: { style: 'light' },
            },
          },
          xaxis: {
            anchor: 'y',
            domain: [0.0, 1.0],
            title: { text: 'Ownership Company' },
            categoryorder: 'array',
            categoryarray: [
              'NextEra Energy',
              'CECEP Solar Energy Technology Co., Ltd.',
              'CGN Solar Energy Development Co., Ltd.',
              'Solatio Energia',
              'Adani Green Energy',
              'China Nuclear Exchange Energy Co., Ltd.',
              'EDF Renewables',
              'China Three Gorges New Energy (Group) Co., Ltd.',
              'Dominion Energy',
              'Duke Energy',
            ],
          },
          yaxis: {
            anchor: 'x',
            domain: [0.0, 1.0],
            title: { text: 'Amount' },
            showspikes: true,
            spikethickness: 2,
            spikemode: 'across',
          },
          legend: {
            title: { text: 'Ownership:', font: { size: 16 } },
            tracegroupgap: 0,
            font: { size: 12 },
          },
          title: {
            text: 'Total solar farms per Ownership',
            font: { size: 22 },
          },
          barmode: 'relative',
          height: 600,
          // width: 877,
          font: { size: 16 },
          uniformtext: { mode: 'hide' },
          spikedistance: 500,
          hoverdistance: 25,
        },
        { responsive: true },
      )
    }
  }, [])
  return (
    <div
      id='bbc70df4-65c8-4f19-a70c-0485833025e3'
      className='plotly-graph-div'
      style={{ height: '600px', width: '100%' }}
    ></div>
  )
}
